export interface CurrencyDef {
  code: string;
  symbol: string;
  label: string;
  unitSingular: string;
  unitPlural: string;
  locale: string;
  decimals: number;
  flag: string;
  country: string;
}

export const CURRENCIES: CurrencyDef[] = [
  { code: "MRU", symbol: "MRU", label: "Ouguiya mauritanienne", unitSingular: "OUGUIYA", unitPlural: "OUGUIYAS", locale: "fr-MR", decimals: 2, flag: "🇲🇷", country: "Mauritanie" },
  { code: "USD", symbol: "$",   label: "Dollar américain", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-US", decimals: 2, flag: "🇺🇸", country: "États-Unis" },
  { code: "EUR", symbol: "€",   label: "Euro", unitSingular: "EURO", unitPlural: "EUROS", locale: "fr-FR", decimals: 2, flag: "🇪🇺", country: "Zone euro" },
  { code: "GBP", symbol: "£",   label: "Livre sterling", unitSingular: "LIVRE", unitPlural: "LIVRES", locale: "en-GB", decimals: 2, flag: "🇬🇧", country: "Royaume-Uni" },
  { code: "JPY", symbol: "¥",   label: "Yen japonais", unitSingular: "YEN", unitPlural: "YENS", locale: "ja-JP", decimals: 0, flag: "🇯🇵", country: "Japon" },
  { code: "CNY", symbol: "¥",   label: "Yuan chinois", unitSingular: "YUAN", unitPlural: "YUANS", locale: "zh-CN", decimals: 2, flag: "🇨🇳", country: "Chine" },
  { code: "CHF", symbol: "CHF", label: "Franc suisse", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-CH", decimals: 2, flag: "🇨🇭", country: "Suisse" },
  { code: "CAD", symbol: "C$",  label: "Dollar canadien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "fr-CA", decimals: 2, flag: "🇨🇦", country: "Canada" },
  { code: "AUD", symbol: "A$",  label: "Dollar australien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-AU", decimals: 2, flag: "🇦🇺", country: "Australie" },
  { code: "NZD", symbol: "NZ$", label: "Dollar néo-zélandais", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-NZ", decimals: 2, flag: "🇳🇿", country: "Nouvelle-Zélande" },
  { code: "HKD", symbol: "HK$", label: "Dollar de Hong Kong", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "zh-HK", decimals: 2, flag: "🇭🇰", country: "Hong Kong" },
  { code: "SGD", symbol: "S$",  label: "Dollar de Singapour", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-SG", decimals: 2, flag: "🇸🇬", country: "Singapour" },
  { code: "TWD", symbol: "NT$", label: "Dollar taïwanais", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "zh-TW", decimals: 2, flag: "🇹🇼", country: "Taïwan" },
  { code: "KRW", symbol: "₩",   label: "Won sud-coréen", unitSingular: "WON", unitPlural: "WONS", locale: "ko-KR", decimals: 0, flag: "🇰🇷", country: "Corée du Sud" },
  { code: "INR", symbol: "₹",   label: "Roupie indienne", unitSingular: "ROUPIE", unitPlural: "ROUPIES", locale: "hi-IN", decimals: 2, flag: "🇮🇳", country: "Inde" },
  { code: "RUB", symbol: "₽",   label: "Rouble russe", unitSingular: "ROUBLE", unitPlural: "ROUBLES", locale: "ru-RU", decimals: 2, flag: "🇷🇺", country: "Russie" },
  { code: "BRL", symbol: "R$",  label: "Réal brésilien", unitSingular: "RÉAL", unitPlural: "RÉAUX", locale: "pt-BR", decimals: 2, flag: "🇧🇷", country: "Brésil" },
  { code: "MXN", symbol: "$",   label: "Peso mexicain", unitSingular: "PESO", unitPlural: "PESOS", locale: "es-MX", decimals: 2, flag: "🇲🇽", country: "Mexique" },
  { code: "ARS", symbol: "$",   label: "Peso argentin", unitSingular: "PESO", unitPlural: "PESOS", locale: "es-AR", decimals: 2, flag: "🇦🇷", country: "Argentine" },
  { code: "CLP", symbol: "$",   label: "Peso chilien", unitSingular: "PESO", unitPlural: "PESOS", locale: "es-CL", decimals: 0, flag: "🇨🇱", country: "Chili" },
  { code: "COP", symbol: "$",   label: "Peso colombien", unitSingular: "PESO", unitPlural: "PESOS", locale: "es-CO", decimals: 2, flag: "🇨🇴", country: "Colombie" },
  { code: "PEN", symbol: "S/",  label: "Sol péruvien", unitSingular: "SOL", unitPlural: "SOLES", locale: "es-PE", decimals: 2, flag: "🇵🇪", country: "Pérou" },
  { code: "UYU", symbol: "$U",  label: "Peso uruguayen", unitSingular: "PESO", unitPlural: "PESOS", locale: "es-UY", decimals: 2, flag: "🇺🇾", country: "Uruguay" },
  { code: "VES", symbol: "Bs.", label: "Bolívar vénézuélien", unitSingular: "BOLIVAR", unitPlural: "BOLIVARS", locale: "es-VE", decimals: 2, flag: "🇻🇪", country: "Venezuela" },
  { code: "BOB", symbol: "Bs.", label: "Boliviano", unitSingular: "BOLIVIANO", unitPlural: "BOLIVIANOS", locale: "es-BO", decimals: 2, flag: "🇧🇴", country: "Bolivie" },
  { code: "PYG", symbol: "₲",   label: "Guarani paraguayen", unitSingular: "GUARANI", unitPlural: "GUARANIS", locale: "es-PY", decimals: 0, flag: "🇵🇾", country: "Paraguay" },
  { code: "DOP", symbol: "RD$", label: "Peso dominicain", unitSingular: "PESO", unitPlural: "PESOS", locale: "es-DO", decimals: 2, flag: "🇩🇴", country: "République dominicaine" },
  { code: "CUP", symbol: "$",   label: "Peso cubain", unitSingular: "PESO", unitPlural: "PESOS", locale: "es-CU", decimals: 2, flag: "🇨🇺", country: "Cuba" },
  { code: "GTQ", symbol: "Q",   label: "Quetzal guatémaltèque", unitSingular: "QUETZAL", unitPlural: "QUETZALES", locale: "es-GT", decimals: 2, flag: "🇬🇹", country: "Guatemala" },
  { code: "HNL", symbol: "L",   label: "Lempira hondurien", unitSingular: "LEMPIRA", unitPlural: "LEMPIRAS", locale: "es-HN", decimals: 2, flag: "🇭🇳", country: "Honduras" },
  { code: "NIO", symbol: "C$",  label: "Córdoba nicaraguayen", unitSingular: "CORDOBA", unitPlural: "CORDOBAS", locale: "es-NI", decimals: 2, flag: "🇳🇮", country: "Nicaragua" },
  { code: "CRC", symbol: "₡",   label: "Colón costaricien", unitSingular: "COLON", unitPlural: "COLONES", locale: "es-CR", decimals: 2, flag: "🇨🇷", country: "Costa Rica" },
  { code: "PAB", symbol: "B/.", label: "Balboa panaméen", unitSingular: "BALBOA", unitPlural: "BALBOAS", locale: "es-PA", decimals: 2, flag: "🇵🇦", country: "Panama" },
  { code: "JMD", symbol: "J$",  label: "Dollar jamaïcain", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-JM", decimals: 2, flag: "🇯🇲", country: "Jamaïque" },
  { code: "TTD", symbol: "TT$", label: "Dollar trinidadien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-TT", decimals: 2, flag: "🇹🇹", country: "Trinité-et-Tobago" },
  { code: "BBD", symbol: "Bds$",label: "Dollar barbadien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-BB", decimals: 2, flag: "🇧🇧", country: "Barbade" },
  { code: "BSD", symbol: "B$",  label: "Dollar bahaméen", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-BS", decimals: 2, flag: "🇧🇸", country: "Bahamas" },
  { code: "BZD", symbol: "BZ$", label: "Dollar bélizéen", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-BZ", decimals: 2, flag: "🇧🇿", country: "Belize" },
  { code: "XCD", symbol: "EC$", label: "Dollar des Caraïbes orientales", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-029", decimals: 2, flag: "🇦🇬", country: "Caraïbes orientales" },
  { code: "HTG", symbol: "G",   label: "Gourde haïtienne", unitSingular: "GOURDE", unitPlural: "GOURDES", locale: "fr-HT", decimals: 2, flag: "🇭🇹", country: "Haïti" },
  { code: "GYD", symbol: "GY$", label: "Dollar guyanien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-GY", decimals: 2, flag: "🇬🇾", country: "Guyana" },
  { code: "SRD", symbol: "Sr$", label: "Dollar surinamais", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "nl-SR", decimals: 2, flag: "🇸🇷", country: "Suriname" },
  { code: "DKK", symbol: "kr",  label: "Couronne danoise", unitSingular: "COURONNE", unitPlural: "COURONNES", locale: "da-DK", decimals: 2, flag: "🇩🇰", country: "Danemark" },
  { code: "SEK", symbol: "kr",  label: "Couronne suédoise", unitSingular: "COURONNE", unitPlural: "COURONNES", locale: "sv-SE", decimals: 2, flag: "🇸🇪", country: "Suède" },
  { code: "NOK", symbol: "kr",  label: "Couronne norvégienne", unitSingular: "COURONNE", unitPlural: "COURONNES", locale: "nb-NO", decimals: 2, flag: "🇳🇴", country: "Norvège" },
  { code: "ISK", symbol: "kr",  label: "Couronne islandaise", unitSingular: "COURONNE", unitPlural: "COURONNES", locale: "is-IS", decimals: 0, flag: "🇮🇸", country: "Islande" },
  { code: "PLN", symbol: "zł",  label: "Zloty polonais", unitSingular: "ZLOTY", unitPlural: "ZLOTYS", locale: "pl-PL", decimals: 2, flag: "🇵🇱", country: "Pologne" },
  { code: "CZK", symbol: "Kč",  label: "Couronne tchèque", unitSingular: "COURONNE", unitPlural: "COURONNES", locale: "cs-CZ", decimals: 2, flag: "🇨🇿", country: "Tchéquie" },
  { code: "HUF", symbol: "Ft",  label: "Forint hongrois", unitSingular: "FORINT", unitPlural: "FORINTS", locale: "hu-HU", decimals: 0, flag: "🇭🇺", country: "Hongrie" },
  { code: "RON", symbol: "lei", label: "Leu roumain", unitSingular: "LEU", unitPlural: "LEI", locale: "ro-RO", decimals: 2, flag: "🇷🇴", country: "Roumanie" },
  { code: "BGN", symbol: "лв",  label: "Lev bulgare", unitSingular: "LEV", unitPlural: "LEVA", locale: "bg-BG", decimals: 2, flag: "🇧🇬", country: "Bulgarie" },
  { code: "HRK", symbol: "kn",  label: "Kuna croate", unitSingular: "KUNA", unitPlural: "KUNAS", locale: "hr-HR", decimals: 2, flag: "🇭🇷", country: "Croatie" },
  { code: "RSD", symbol: "дин",label: "Dinar serbe", unitSingular: "DINAR", unitPlural: "DINARS", locale: "sr-RS", decimals: 2, flag: "🇷🇸", country: "Serbie" },
  { code: "BAM", symbol: "KM",  label: "Mark convertible bosnien", unitSingular: "MARK", unitPlural: "MARKS", locale: "bs-BA", decimals: 2, flag: "🇧🇦", country: "Bosnie-Herzégovine" },
  { code: "MKD", symbol: "ден",label: "Denar macédonien", unitSingular: "DENAR", unitPlural: "DENARS", locale: "mk-MK", decimals: 2, flag: "🇲🇰", country: "Macédoine du Nord" },
  { code: "ALL", symbol: "L",   label: "Lek albanais", unitSingular: "LEK", unitPlural: "LEKS", locale: "sq-AL", decimals: 2, flag: "🇦🇱", country: "Albanie" },
  { code: "MDL", symbol: "L",   label: "Leu moldave", unitSingular: "LEU", unitPlural: "LEI", locale: "ro-MD", decimals: 2, flag: "🇲🇩", country: "Moldavie" },
  { code: "UAH", symbol: "₴",   label: "Hryvnia ukrainienne", unitSingular: "HRYVNIA", unitPlural: "HRYVNIAS", locale: "uk-UA", decimals: 2, flag: "🇺🇦", country: "Ukraine" },
  { code: "BYN", symbol: "Br",  label: "Rouble biélorusse", unitSingular: "ROUBLE", unitPlural: "ROUBLES", locale: "be-BY", decimals: 2, flag: "🇧🇾", country: "Biélorussie" },
  { code: "GEL", symbol: "₾",   label: "Lari géorgien", unitSingular: "LARI", unitPlural: "LARIS", locale: "ka-GE", decimals: 2, flag: "🇬🇪", country: "Géorgie" },
  { code: "AMD", symbol: "֏",   label: "Dram arménien", unitSingular: "DRAM", unitPlural: "DRAMS", locale: "hy-AM", decimals: 2, flag: "🇦🇲", country: "Arménie" },
  { code: "AZN", symbol: "₼",   label: "Manat azerbaïdjanais", unitSingular: "MANAT", unitPlural: "MANATS", locale: "az-AZ", decimals: 2, flag: "🇦🇿", country: "Azerbaïdjan" },
  { code: "TRY", symbol: "₺",   label: "Livre turque", unitSingular: "LIVRE", unitPlural: "LIVRES", locale: "tr-TR", decimals: 2, flag: "🇹🇷", country: "Turquie" },
  { code: "ILS", symbol: "₪",   label: "Shekel israélien", unitSingular: "SHEKEL", unitPlural: "SHEKELS", locale: "he-IL", decimals: 2, flag: "🇮🇱", country: "Israël" },
  { code: "AED", symbol: "AED", label: "Dirham émirati", unitSingular: "DIRHAM", unitPlural: "DIRHAMS", locale: "ar-AE", decimals: 2, flag: "🇦🇪", country: "Émirats arabes unis" },
  { code: "SAR", symbol: "SAR", label: "Riyal saoudien", unitSingular: "RIYAL", unitPlural: "RIYALS", locale: "ar-SA", decimals: 2, flag: "🇸🇦", country: "Arabie saoudite" },
  { code: "QAR", symbol: "QAR", label: "Riyal qatari", unitSingular: "RIYAL", unitPlural: "RIYALS", locale: "ar-QA", decimals: 2, flag: "🇶🇦", country: "Qatar" },
  { code: "KWD", symbol: "KWD", label: "Dinar koweïtien", unitSingular: "DINAR", unitPlural: "DINARS", locale: "ar-KW", decimals: 3, flag: "🇰🇼", country: "Koweït" },
  { code: "BHD", symbol: "BHD", label: "Dinar bahreïni", unitSingular: "DINAR", unitPlural: "DINARS", locale: "ar-BH", decimals: 3, flag: "🇧🇭", country: "Bahreïn" },
  { code: "OMR", symbol: "OMR", label: "Riyal omanais", unitSingular: "RIYAL", unitPlural: "RIYALS", locale: "ar-OM", decimals: 3, flag: "🇴🇲", country: "Oman" },
  { code: "JOD", symbol: "JOD", label: "Dinar jordanien", unitSingular: "DINAR", unitPlural: "DINARS", locale: "ar-JO", decimals: 3, flag: "🇯🇴", country: "Jordanie" },
  { code: "LBP", symbol: "L£",  label: "Livre libanaise", unitSingular: "LIVRE", unitPlural: "LIVRES", locale: "ar-LB", decimals: 2, flag: "🇱🇧", country: "Liban" },
  { code: "SYP", symbol: "S£",  label: "Livre syrienne", unitSingular: "LIVRE", unitPlural: "LIVRES", locale: "ar-SY", decimals: 2, flag: "🇸🇾", country: "Syrie" },
  { code: "IQD", symbol: "IQD", label: "Dinar irakien", unitSingular: "DINAR", unitPlural: "DINARS", locale: "ar-IQ", decimals: 3, flag: "🇮🇶", country: "Irak" },
  { code: "IRR", symbol: "﷼",   label: "Rial iranien", unitSingular: "RIAL", unitPlural: "RIALS", locale: "fa-IR", decimals: 2, flag: "🇮🇷", country: "Iran" },
  { code: "YER", symbol: "﷼",   label: "Rial yéménite", unitSingular: "RIAL", unitPlural: "RIALS", locale: "ar-YE", decimals: 2, flag: "🇾🇪", country: "Yémen" },
  { code: "EGP", symbol: "E£",  label: "Livre égyptienne", unitSingular: "LIVRE", unitPlural: "LIVRES", locale: "ar-EG", decimals: 2, flag: "🇪🇬", country: "Égypte" },
  { code: "MAD", symbol: "DH",  label: "Dirham marocain", unitSingular: "DIRHAM", unitPlural: "DIRHAMS", locale: "fr-MA", decimals: 2, flag: "🇲🇦", country: "Maroc" },
  { code: "DZD", symbol: "DA",  label: "Dinar algérien", unitSingular: "DINAR", unitPlural: "DINARS", locale: "fr-DZ", decimals: 2, flag: "🇩🇿", country: "Algérie" },
  { code: "TND", symbol: "DT",  label: "Dinar tunisien", unitSingular: "DINAR", unitPlural: "DINARS", locale: "fr-TN", decimals: 3, flag: "🇹🇳", country: "Tunisie" },
  { code: "LYD", symbol: "LD",  label: "Dinar libyen", unitSingular: "DINAR", unitPlural: "DINARS", locale: "ar-LY", decimals: 3, flag: "🇱🇾", country: "Libye" },
  { code: "SDG", symbol: "SDG", label: "Livre soudanaise", unitSingular: "LIVRE", unitPlural: "LIVRES", locale: "ar-SD", decimals: 2, flag: "🇸🇩", country: "Soudan" },
  { code: "SSP", symbol: "SSP", label: "Livre sud-soudanaise", unitSingular: "LIVRE", unitPlural: "LIVRES", locale: "en-SS", decimals: 2, flag: "🇸🇸", country: "Soudan du Sud" },
  { code: "ETB", symbol: "Br",  label: "Birr éthiopien", unitSingular: "BIRR", unitPlural: "BIRRS", locale: "am-ET", decimals: 2, flag: "🇪🇹", country: "Éthiopie" },
  { code: "ERN", symbol: "Nfk", label: "Nakfa érythréen", unitSingular: "NAKFA", unitPlural: "NAKFAS", locale: "ti-ER", decimals: 2, flag: "🇪🇷", country: "Érythrée" },
  { code: "DJF", symbol: "Fdj", label: "Franc djiboutien", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-DJ", decimals: 0, flag: "🇩🇯", country: "Djibouti" },
  { code: "SOS", symbol: "Sh",  label: "Shilling somalien", unitSingular: "SHILLING", unitPlural: "SHILLINGS", locale: "so-SO", decimals: 2, flag: "🇸🇴", country: "Somalie" },
  { code: "KES", symbol: "KSh", label: "Shilling kényan", unitSingular: "SHILLING", unitPlural: "SHILLINGS", locale: "sw-KE", decimals: 2, flag: "🇰🇪", country: "Kenya" },
  { code: "UGX", symbol: "USh", label: "Shilling ougandais", unitSingular: "SHILLING", unitPlural: "SHILLINGS", locale: "sw-UG", decimals: 0, flag: "🇺🇬", country: "Ouganda" },
  { code: "TZS", symbol: "TSh", label: "Shilling tanzanien", unitSingular: "SHILLING", unitPlural: "SHILLINGS", locale: "sw-TZ", decimals: 2, flag: "🇹🇿", country: "Tanzanie" },
  { code: "RWF", symbol: "RF",  label: "Franc rwandais", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-RW", decimals: 0, flag: "🇷🇼", country: "Rwanda" },
  { code: "BIF", symbol: "FBu", label: "Franc burundais", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-BI", decimals: 0, flag: "🇧🇮", country: "Burundi" },
  { code: "CDF", symbol: "FC",  label: "Franc congolais", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-CD", decimals: 2, flag: "🇨🇩", country: "RD Congo" },
  { code: "AOA", symbol: "Kz",  label: "Kwanza angolais", unitSingular: "KWANZA", unitPlural: "KWANZAS", locale: "pt-AO", decimals: 2, flag: "🇦🇴", country: "Angola" },
  { code: "ZMW", symbol: "ZK",  label: "Kwacha zambien", unitSingular: "KWACHA", unitPlural: "KWACHAS", locale: "en-ZM", decimals: 2, flag: "🇿🇲", country: "Zambie" },
  { code: "MWK", symbol: "MK",  label: "Kwacha malawite", unitSingular: "KWACHA", unitPlural: "KWACHAS", locale: "en-MW", decimals: 2, flag: "🇲🇼", country: "Malawi" },
  { code: "ZWL", symbol: "Z$",  label: "Dollar zimbabwéen", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-ZW", decimals: 2, flag: "🇿🇼", country: "Zimbabwe" },
  { code: "BWP", symbol: "P",   label: "Pula botswanais", unitSingular: "PULA", unitPlural: "PULAS", locale: "en-BW", decimals: 2, flag: "🇧🇼", country: "Botswana" },
  { code: "NAD", symbol: "N$",  label: "Dollar namibien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-NA", decimals: 2, flag: "🇳🇦", country: "Namibie" },
  { code: "ZAR", symbol: "R",   label: "Rand sud-africain", unitSingular: "RAND", unitPlural: "RANDS", locale: "en-ZA", decimals: 2, flag: "🇿🇦", country: "Afrique du Sud" },
  { code: "LSL", symbol: "L",   label: "Loti lesothan", unitSingular: "LOTI", unitPlural: "LOTIS", locale: "en-LS", decimals: 2, flag: "🇱🇸", country: "Lesotho" },
  { code: "SZL", symbol: "E",   label: "Lilangeni swazi", unitSingular: "LILANGENI", unitPlural: "EMALANGENI", locale: "en-SZ", decimals: 2, flag: "🇸🇿", country: "Eswatini" },
  { code: "MZN", symbol: "MT",  label: "Metical mozambicain", unitSingular: "METICAL", unitPlural: "METICAIS", locale: "pt-MZ", decimals: 2, flag: "🇲🇿", country: "Mozambique" },
  { code: "MGA", symbol: "Ar",  label: "Ariary malgache", unitSingular: "ARIARY", unitPlural: "ARIARYS", locale: "fr-MG", decimals: 2, flag: "🇲🇬", country: "Madagascar" },
  { code: "MUR", symbol: "₨",   label: "Roupie mauricienne", unitSingular: "ROUPIE", unitPlural: "ROUPIES", locale: "fr-MU", decimals: 2, flag: "🇲🇺", country: "Maurice" },
  { code: "SCR", symbol: "₨",   label: "Roupie seychelloise", unitSingular: "ROUPIE", unitPlural: "ROUPIES", locale: "fr-SC", decimals: 2, flag: "🇸🇨", country: "Seychelles" },
  { code: "KMF", symbol: "CF",  label: "Franc comorien", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-KM", decimals: 0, flag: "🇰🇲", country: "Comores" },
  { code: "CVE", symbol: "$",   label: "Escudo cap-verdien", unitSingular: "ESCUDO", unitPlural: "ESCUDOS", locale: "pt-CV", decimals: 2, flag: "🇨🇻", country: "Cap-Vert" },
  { code: "STN", symbol: "Db",  label: "Dobra santoméen", unitSingular: "DOBRA", unitPlural: "DOBRAS", locale: "pt-ST", decimals: 2, flag: "🇸🇹", country: "Sao Tomé-et-Principe" },
  { code: "GMD", symbol: "D",   label: "Dalasi gambien", unitSingular: "DALASI", unitPlural: "DALASIS", locale: "en-GM", decimals: 2, flag: "🇬🇲", country: "Gambie" },
  { code: "GNF", symbol: "FG",  label: "Franc guinéen", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-GN", decimals: 0, flag: "🇬🇳", country: "Guinée" },
  { code: "SLE", symbol: "Le",  label: "Leone sierra-léonais", unitSingular: "LEONE", unitPlural: "LEONES", locale: "en-SL", decimals: 2, flag: "🇸🇱", country: "Sierra Leone" },
  { code: "LRD", symbol: "L$",  label: "Dollar libérien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-LR", decimals: 2, flag: "🇱🇷", country: "Libéria" },
  { code: "GHS", symbol: "₵",   label: "Cedi ghanéen", unitSingular: "CEDI", unitPlural: "CEDIS", locale: "en-GH", decimals: 2, flag: "🇬🇭", country: "Ghana" },
  { code: "NGN", symbol: "₦",   label: "Naira nigérian", unitSingular: "NAIRA", unitPlural: "NAIRAS", locale: "en-NG", decimals: 2, flag: "🇳🇬", country: "Nigéria" },
  { code: "XOF", symbol: "CFA", label: "Franc CFA (UEMOA)", unitSingular: "FRANC CFA", unitPlural: "FRANCS CFA", locale: "fr-FR", decimals: 0, flag: "🇸🇳", country: "UEMOA" },
  { code: "XAF", symbol: "FCFA",label: "Franc CFA (CEMAC)", unitSingular: "FRANC CFA", unitPlural: "FRANCS CFA", locale: "fr-FR", decimals: 0, flag: "🇨🇲", country: "CEMAC" },
  { code: "XPF", symbol: "F",   label: "Franc CFP", unitSingular: "FRANC", unitPlural: "FRANCS", locale: "fr-FR", decimals: 0, flag: "🇵🇫", country: "Pacifique" },
  { code: "PKR", symbol: "₨",   label: "Roupie pakistanaise", unitSingular: "ROUPIE", unitPlural: "ROUPIES", locale: "ur-PK", decimals: 2, flag: "🇵🇰", country: "Pakistan" },
  { code: "BDT", symbol: "৳",   label: "Taka bangladais", unitSingular: "TAKA", unitPlural: "TAKAS", locale: "bn-BD", decimals: 2, flag: "🇧🇩", country: "Bangladesh" },
  { code: "LKR", symbol: "Rs",  label: "Roupie srilankaise", unitSingular: "ROUPIE", unitPlural: "ROUPIES", locale: "si-LK", decimals: 2, flag: "🇱🇰", country: "Sri Lanka" },
  { code: "NPR", symbol: "₨",   label: "Roupie népalaise", unitSingular: "ROUPIE", unitPlural: "ROUPIES", locale: "ne-NP", decimals: 2, flag: "🇳🇵", country: "Népal" },
  { code: "BTN", symbol: "Nu.", label: "Ngultrum bhoutanais", unitSingular: "NGULTRUM", unitPlural: "NGULTRUMS", locale: "dz-BT", decimals: 2, flag: "🇧🇹", country: "Bhoutan" },
  { code: "MVR", symbol: "Rf",  label: "Rufiyaa maldivien", unitSingular: "RUFIYAA", unitPlural: "RUFIYAAS", locale: "dv-MV", decimals: 2, flag: "🇲🇻", country: "Maldives" },
  { code: "AFN", symbol: "؋",   label: "Afghani afghan", unitSingular: "AFGHANI", unitPlural: "AFGHANIS", locale: "fa-AF", decimals: 2, flag: "🇦🇫", country: "Afghanistan" },
  { code: "KZT", symbol: "₸",   label: "Tenge kazakh", unitSingular: "TENGE", unitPlural: "TENGES", locale: "kk-KZ", decimals: 2, flag: "🇰🇿", country: "Kazakhstan" },
  { code: "UZS", symbol: "сўм",label: "Sum ouzbek", unitSingular: "SUM", unitPlural: "SUMS", locale: "uz-UZ", decimals: 2, flag: "🇺🇿", country: "Ouzbékistan" },
  { code: "TJS", symbol: "SM",  label: "Somoni tadjik", unitSingular: "SOMONI", unitPlural: "SOMONIS", locale: "tg-TJ", decimals: 2, flag: "🇹🇯", country: "Tadjikistan" },
  { code: "TMT", symbol: "T",   label: "Manat turkmène", unitSingular: "MANAT", unitPlural: "MANATS", locale: "tk-TM", decimals: 2, flag: "🇹🇲", country: "Turkménistan" },
  { code: "KGS", symbol: "с",   label: "Som kirghize", unitSingular: "SOM", unitPlural: "SOMS", locale: "ky-KG", decimals: 2, flag: "🇰🇬", country: "Kirghizistan" },
  { code: "MNT", symbol: "₮",   label: "Tugrik mongol", unitSingular: "TUGRIK", unitPlural: "TUGRIKS", locale: "mn-MN", decimals: 2, flag: "🇲🇳", country: "Mongolie" },
  { code: "THB", symbol: "฿",   label: "Baht thaïlandais", unitSingular: "BAHT", unitPlural: "BAHTS", locale: "th-TH", decimals: 2, flag: "🇹🇭", country: "Thaïlande" },
  { code: "VND", symbol: "₫",   label: "Dong vietnamien", unitSingular: "DONG", unitPlural: "DONGS", locale: "vi-VN", decimals: 0, flag: "🇻🇳", country: "Viêt Nam" },
  { code: "LAK", symbol: "₭",   label: "Kip laotien", unitSingular: "KIP", unitPlural: "KIPS", locale: "lo-LA", decimals: 2, flag: "🇱🇦", country: "Laos" },
  { code: "KHR", symbol: "៛",   label: "Riel cambodgien", unitSingular: "RIEL", unitPlural: "RIELS", locale: "km-KH", decimals: 2, flag: "🇰🇭", country: "Cambodge" },
  { code: "MMK", symbol: "K",   label: "Kyat birman", unitSingular: "KYAT", unitPlural: "KYATS", locale: "my-MM", decimals: 2, flag: "🇲🇲", country: "Myanmar" },
  { code: "MYR", symbol: "RM",  label: "Ringgit malaisien", unitSingular: "RINGGIT", unitPlural: "RINGGITS", locale: "ms-MY", decimals: 2, flag: "🇲🇾", country: "Malaisie" },
  { code: "IDR", symbol: "Rp",  label: "Roupie indonésienne", unitSingular: "ROUPIE", unitPlural: "ROUPIES", locale: "id-ID", decimals: 2, flag: "🇮🇩", country: "Indonésie" },
  { code: "PHP", symbol: "₱",   label: "Peso philippin", unitSingular: "PESO", unitPlural: "PESOS", locale: "fil-PH", decimals: 2, flag: "🇵🇭", country: "Philippines" },
  { code: "BND", symbol: "B$",  label: "Dollar de Brunei", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "ms-BN", decimals: 2, flag: "🇧🇳", country: "Brunei" },
  { code: "PGK", symbol: "K",   label: "Kina papouasien", unitSingular: "KINA", unitPlural: "KINAS", locale: "en-PG", decimals: 2, flag: "🇵🇬", country: "Papouasie-Nouvelle-Guinée" },
  { code: "FJD", symbol: "FJ$", label: "Dollar fidjien", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-FJ", decimals: 2, flag: "🇫🇯", country: "Fidji" },
  { code: "SBD", symbol: "SI$", label: "Dollar des Salomon", unitSingular: "DOLLAR", unitPlural: "DOLLARS", locale: "en-SB", decimals: 2, flag: "🇸🇧", country: "Salomon" },
  { code: "VUV", symbol: "VT",  label: "Vatu vanuatuan", unitSingular: "VATU", unitPlural: "VATUS", locale: "fr-VU", decimals: 0, flag: "🇻🇺", country: "Vanuatu" },
  { code: "WST", symbol: "WS$", label: "Tala samoan", unitSingular: "TALA", unitPlural: "TALAS", locale: "en-WS", decimals: 2, flag: "🇼🇸", country: "Samoa" },
  { code: "TOP", symbol: "T$",  label: "Pa'anga tongan", unitSingular: "PAANGA", unitPlural: "PAANGAS", locale: "en-TO", decimals: 2, flag: "🇹🇴", country: "Tonga" },
];

export const DEFAULT_CURRENCY: CurrencyDef = CURRENCIES[0];

export function getCurrency(code?: string | null): CurrencyDef {
  if (!code) return DEFAULT_CURRENCY;
  return CURRENCIES.find((c) => c.code.toUpperCase() === code.toUpperCase()) ?? DEFAULT_CURRENCY;
}
